version: '3.6'

services:
  mock-drs:
    image: mock-drs:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongo
    ports:
      - "9101:9101"
    command: bash -c "cd /app/; python mock_drs/Server.py"

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ../data/db:/data/db
    expose:
      - "27017"
