paths:
  /update-db:
    post:
      summary: Object id's in the array that need to be added to the db
      operationId: UpdateDatabaseObjects
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: ''
          schema:
            $ref: '#/definitions/UpdateObject'
          required: true
      responses:
        200:
          description: "200 response"
          schema:
              $ref: '#/definitions/UpdatedDB'
      tags:
        - DataRepositoryService
      x-swagger-router-controller: ga4gh.drs.server
definitions:
  UpdatedDB:
    type: object
    properties:
      objects:
        type: array
        items:
          type: string
  UpdateObject:
    type: object
    properties:
      clear_db:
        type: boolean
      data_objects:
        type: array
        items:
          $ref: '#/definitions/Object'
